ci: Redo arm runner switch

diff --git a/.github/workflows/frontend_deploy.yml b/.github/workflows/frontend_deploy.yml
--- a/.github/workflows/frontend_deploy.yml
+++ b/.github/workflows/frontend_deploy.yml
@@ -11,25 +11,31 @@ on:
 
 jobs:
   docker:
-    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        include:
+          - os: ubuntu-24.04
+            platform: amd64
+          - os: ubuntu-24.04-arm
+            platform: arm64
+    runs-on: ${{matrix.os}}
     timeout-minutes: 80
     permissions:
       packages: write
     concurrency:
-      group: build_push_docker_frontend_prod
+      group: ${{matrix.os}}-build_push_docker_frontend_prod
       cancel-in-progress: true
     steps:
-      # 2024-11-16: default-avail: 21G, needs: 20 GB, post-cleanup-avail: 53G
+      # 2025-02-02: needs: 20 GB, post-cleanup-avail: 57G
       - name: Free up space
         run: |
-          df -h|grep "/dev/root"
-          sudo rm -rf /opt/* /usr/local/.ghcup /swapfile
-          sudo rm -rf /usr/local/lib/android
-          sudo rm -rf /usr/share/dotnet /usr/share/swift
-          sudo rm -rf /usr/local/share/boost /usr/local/share/powershell
-          sudo rm -rf /usr/lib/google-cloud-sdk /usr/lib/jvm
+          sudo du -xh --max-depth=3 / 2>/dev/null | sort -rh | head -40 || true
+          sudo rm -rf /usr/share/swift /usr/lib/jvm /opt/* \
+            /usr/lib/dotnet /usr/share/az_* /usr/local/lib/android \
+            /usr/local/lib/android /usr/share/dotnet \
+            /usr/local/share/boost /usr/local/share/powershell \
+            /usr/lib/google-cloud-sdk /var/lib/apt/lists/*
           sudo apt-get clean
-          sudo rm -rf /var/lib/apt/lists/*
           df -h|grep "/dev/root"
 
       - uses: actions/checkout@v4
@@ -51,16 +57,49 @@ jobs:
           file: frontend/Dockerfile
           push: ${{ github.event_name != 'pull_request' }}
           no-cache: true
-          platforms: linux/amd64,linux/arm64
+          platforms: linux/${{ matrix.platform }}
+          provenance: false
           build-args: |
             NEXT_PUBLIC_IS_PRODUCTION=true
             ENABLE_SENTRY=true
             SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
             GITHUB_SHA=${{ github.sha }}
           tags: |
-            ghcr.io/flathub-infra/frontend:${{ github.sha }}
-            ghcr.io/flathub-infra/frontend:latest
+            ghcr.io/${{ github.repository_owner }}/frontend:${{ github.sha }}-${{ matrix.platform }}
+            ghcr.io/${{ github.repository_owner }}/frontend:latest-${{ matrix.platform }}
           labels: |
             org.opencontainers.image.revision=${{ github.sha }}
             org.opencontainers.image.source=ssh://git@github.com:${{ github.repository }}.git
             org.opencontainers.image.url=https://github.com/${{ github.repository }}
+
+  docker-manifest:
+    if: ${{ github.event_name != 'pull_request' }}
+    runs-on: ubuntu-latest
+    timeout-minutes: 30
+    needs:
+      - docker
+    permissions:
+      packages: write
+    steps:
+      - name: Login to ghcr.io
+        uses: docker/login-action@v3
+        with:
+          registry: ghcr.io
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Create and push frontend manifest
+        run: |
+          docker manifest create \
+            ghcr.io/${{ github.repository_owner }}/frontend:${{ github.sha }} \
+            --amend ghcr.io/${{ github.repository_owner }}/frontend:${{ github.sha }}-amd64 \
+            --amend ghcr.io/${{ github.repository_owner }}/frontend:${{ github.sha }}-arm64
+
+          docker manifest push ghcr.io/${{ github.repository_owner }}/frontend:${{ github.sha }}
+
+          docker manifest create \
+            ghcr.io/${{ github.repository_owner }}/frontend:latest \
+            --amend ghcr.io/${{ github.repository_owner }}/frontend:${{ github.sha }}-amd64 \
+            --amend ghcr.io/${{ github.repository_owner }}/frontend:${{ github.sha }}-arm64
+
+          docker manifest push ghcr.io/${{ github.repository_owner }}/frontend:latest
